<a href="https://colab.research.google.com/github/moghanapriya-27/Datascience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.arange(12).reshape(3,4)
b=a>4
print(b)
a[b]=1
print(b)
print(a[b])
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[1 1 1 1 1 1 1]
[[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy as np
names=np.array(["bob","jope","joe","bob","jope","jope","jope"])
data=np.arange(28).reshape(7,4)
print(data[names=="bob"])
print(data[names=="bob",:2])
print(data[names=="bob",3])

[[ 0  1  2  3]
 [12 13 14 15]]
[[ 0  1]
 [12 13]]
[ 3 15]


In [ ]:
#basic indexing and slicing
import numpy as np
a=np.arange(10)
print("the original array is :",a)
print(a[0:4])
a[0:4]=3
print(a)
print(a[::3])
print(a[4:7])
view=a[1:2]=3
print(view)
print(a[::-3])


the original array is : [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[3 3 3 3 4 5 6 7 8 9]
[3 3 6 9]
[4 5 6]
3
[9 6 3 3]


In [ ]:
import numpy as np
a = np.arange(16).reshape(8,2)
print("Original array 'a':")
print(a)

a_copy = a[:].copy()
# Modify an element in the copy
a_copy[1,1] = 99

print("\nModified copy 'a_copy':")
print(a_copy)

print("\nOriginal array 'a' after modifying the copy:")
print(a)

Original array 'a':
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

Modified copy 'a_copy':
[[ 0  1]
 [ 2 99]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

Original array 'a' after modifying the copy:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
MOGHANAPRIYA R
231801102